language: node_js
node_js:
- '6'
addons:
    apt: 
        sources:
        - heroku
        packages:
        - heroku-toolbelt
install:
- npm install
script:
- heroku app:create ci-workshop-test-1-f2

after_success:
 - heroku app:create ci-workshop-test-1-f2
 - git remote add heroku git@heroku.com:HEROKU_APP_NAME.git
 - echo ">>>>>> hello"
 - echo "Host heroku.com" >> ~/.ssh/config
 - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
 - echo "   CheckHostIP no" >> ~/.ssh/config
 - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
 - yes | heroku keys:add
 - yes | git push heroku master
