language: node_js
node_js:
- '6'
install:
- npm install
script:
- true
before_install:
 -wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

after_success:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - git remote add heroku git@heroku.com:HEROKU_APP_NAME.git
  - echo ">>>>>> hello"
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - yes | heroku keys:add
  - yes | git push heroku master
  on:
    repo: MityaRo/test-1
